package com.alieba.app

import android.app.*
import android.os.*
import android.graphics.*
import android.graphics.drawable.*
import android.view.*
import android.widget.*
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import kotlin.math.sin

class MainActivity : Activity() {
    private val brown=0xff8a4e32.toInt(); private val ink=0xff302823.toInt(); private val cream=0xfffff9f5.toInt()
    override fun onCreate(b:Bundle?){super.onCreate(b); if(Build.VERSION.SDK_INT>=33)requestPermissions(arrayOf("android.permission.POST_NOTIFICATIONS"),7); val v=home();setContentView(v);ViewCompat.setOnApplyWindowInsetsListener(v){x,i->val q=i.getInsets(WindowInsetsCompat.Type.systemBars());x.setPadding(0,q.top,0,q.bottom);i}}
    private fun home():View{
        val root=FrameLayout(this).apply{setBackgroundColor(cream)}
        val scroll=ScrollView(this).apply{isFillViewport=true;setPadding(0,0,0,dp(92))}; val body=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL}
        val hero=FrameLayout(this).apply{layoutParams=LinearLayout.LayoutParams(-1,dp(300));background=getDrawable(R.drawable.mosque_bg)}
        hero.addView(View(this).apply{background=GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,intArrayOf(0x22000000,0x88000000.toInt()))},FrameLayout.LayoutParams(-1,-1))
        hero.addView(TextView(this).apply{text="Ali-eba";textSize=27f;setTextColor(Color.WHITE);typeface=Typeface.DEFAULT_BOLD;setPadding(dp(20),dp(16),0,0)})
        val profile=ImageButton(this).apply{setImageResource(R.drawable.ic_profile);setColorFilter(Color.WHITE);background=GradientDrawable().apply{setColor(0x44000000);shape=GradientDrawable.OVAL};setPadding(dp(9),dp(9),dp(9),dp(9));setOnClickListener{showProfile()}}
        hero.addView(profile,FrameLayout.LayoutParams(dp(48),dp(48),Gravity.TOP or Gravity.END).apply{setMargins(0,dp(10),dp(16),0)})
        hero.addView(BirdSkyView(this),FrameLayout.LayoutParams(-1,dp(190)))
        hero.addView(prayerStrip(),FrameLayout.LayoutParams(-1,dp(80),Gravity.BOTTOM));body.addView(hero)
        val grid=GridLayout(this).apply{columnCount=3;setPadding(dp(12),dp(30),dp(12),dp(26));setBackgroundColor(cream)}
        val items=listOf("Quran" to R.drawable.ic_quran,"Məfatih" to R.drawable.ic_dua,"Əhkam" to R.drawable.ic_rules,"Təqvim" to R.drawable.ic_calendar,"Mərsiyələr" to R.drawable.ic_audio,"Hədis" to R.drawable.ic_hadith,"Məşvərət" to R.drawable.ic_chat,"Kitabxana" to R.drawable.ic_library,"Qiblə" to R.drawable.ic_qibla,"Zikr" to R.drawable.ic_tasbeh,"Ayarlar" to R.drawable.ic_settings)
        items.forEach{(n,ic)->val cell=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;addView(ImageView(this@MainActivity).apply{setImageResource(ic);setColorFilter(brown);setPadding(dp(9),dp(9),dp(9),dp(9))},LinearLayout.LayoutParams(dp(55),dp(55)));addView(TextView(this@MainActivity).apply{text=n;textSize=13.5f;gravity=Gravity.CENTER;setTextColor(ink);maxLines=2},LinearLayout.LayoutParams(-1,dp(38)));if(n=="Ayarlar")setOnClickListener{prayerSettings()}};grid.addView(cell,GridLayout.LayoutParams().apply{width=0;height=dp(100);columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f)})}
        body.addView(grid);scroll.addView(body);root.addView(scroll,FrameLayout.LayoutParams(-1,-1));root.addView(bottomWave(),FrameLayout.LayoutParams(-1,dp(104),Gravity.BOTTOM));return root
    }
    private fun prayerStrip():View{val p=getSharedPreferences("prayer_times",MODE_PRIVATE);val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER;setPadding(dp(5),dp(5),dp(5),dp(8))};listOf("Fəcr" to "05:19","Günəş" to "06:42","Zöhr" to "12:55","Əsr" to "16:19","Məğrib" to "19:26","İşa" to "00:14").forEach{(n,d)->row.addView(TextView(this).apply{text="$n\n${p.getString(n,d)}";textSize=11.5f;gravity=Gravity.CENTER;setTextColor(Color.WHITE);background=GradientDrawable().apply{setColor(0x66000000);cornerRadius=dp(15).toFloat()}},LinearLayout.LayoutParams(0,-1,1f).apply{setMargins(dp(2),0,dp(2),0)})};return row}
    private fun bottomWave():View{val wrap=FrameLayout(this).apply{background=BottomWaveDrawable(Color.WHITE,dp(24).toFloat());elevation=dp(14).toFloat()};val bar=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.BOTTOM;setPadding(dp(16),dp(28),dp(16),dp(6))};fun nav(t:String,ic:Int,active:Boolean=false)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;addView(ImageView(this@MainActivity).apply{setImageResource(ic);setColorFilter(if(active)brown else 0xff77706b.toInt())},LinearLayout.LayoutParams(dp(28),dp(28)));addView(TextView(this@MainActivity).apply{text=t;textSize=11f;setTextColor(if(active)brown else 0xff77706b.toInt())})}};bar.addView(nav("Ana səhifə",R.drawable.ic_home,true),LinearLayout.LayoutParams(0,-1,1f));bar.addView(Space(this),LinearLayout.LayoutParams(0,-1,1f));bar.addView(nav("Profil",R.drawable.ic_profile),LinearLayout.LayoutParams(0,-1,1f).also{});bar.getChildAt(2).setOnClickListener{showProfile()};wrap.addView(bar,FrameLayout.LayoutParams(-1,-1));val ai=TextView(this).apply{text="AI";textSize=19f;typeface=Typeface.DEFAULT_BOLD;gravity=Gravity.CENTER;setTextColor(Color.WHITE);background=GradientDrawable().apply{shape=GradientDrawable.OVAL;setColor(brown);setStroke(dp(5),Color.WHITE)};elevation=dp(18).toFloat();setOnClickListener{Toast.makeText(this@MainActivity,"Ali-eba AI Köməkçi",Toast.LENGTH_SHORT).show()}};wrap.addView(ai,FrameLayout.LayoutParams(dp(72),dp(72),Gravity.TOP or Gravity.CENTER_HORIZONTAL).apply{topMargin=dp(2)});return wrap}
    private fun showProfile(){val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(24),dp(18),dp(24),dp(10))};box.addView(ImageView(this).apply{setImageResource(R.drawable.ic_profile);setColorFilter(brown)},LinearLayout.LayoutParams(-1,dp(70)));box.addView(TextView(this).apply{text="İstifadəçi\nAli-eba Coin: 0";gravity=Gravity.CENTER;textSize=18f;setTextColor(ink);setPadding(0,dp(8),0,dp(14))});fun btn(t:String,click:()->Unit)=Button(this).apply{text=t;setOnClickListener{click()}};box.addView(btn("Google ilə daxil ol"){Toast.makeText(this,"Google giriş üçün google-services.json + SHA-1 tamamlanmalıdır",Toast.LENGTH_LONG).show()});box.addView(btn("Azan vaxtları və tənzimləmələr"){prayerSettings()});val role=getSharedPreferences("account",MODE_PRIVATE).getString("role","user");if(role=="admin")box.addView(btn("Admin Paneli"){Toast.makeText(this,"Admin API paneli",Toast.LENGTH_SHORT).show()});AlertDialog.Builder(this).setTitle("Profil").setView(box).setNegativeButton("Bağla",null).show()}
    private fun prayerSettings(){val names=arrayOf("Fəcr","Günəş","Zöhr","Əsr","Məğrib","İşa");val defaults=arrayOf("05:19","06:42","12:55","16:19","19:26","00:14");val p=getSharedPreferences("prayer_times",MODE_PRIVATE);var i=0;fun next(){if(i>=names.size){Toast.makeText(this,"Azan vaxtları yadda saxlandı",Toast.LENGTH_SHORT).show();recreate();return};val n=names[i];val e=EditText(this).apply{setText(p.getString(n,defaults[i]));hint="HH:mm"};AlertDialog.Builder(this).setTitle("$n vaxtı").setView(e).setPositiveButton("Yadda saxla"){_,_->p.edit().putString(n,e.text.toString()).apply();i++;next()}.setNegativeButton("Bitir",null).show()};next()}
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
}
class BottomWaveDrawable(private val fill:Int,private val amp:Float):Drawable(){private val p=Paint(1).apply{color=fill};override fun draw(c:Canvas){val b=bounds;val w=b.width().toFloat();val x=Path();x.moveTo(0f,amp);x.cubicTo(w*.18f,amp,w*.28f,0f,w*.38f,amp*.25f);x.cubicTo(w*.44f,amp*.5f,w*.44f,amp*1.8f,w*.5f,amp*1.8f);x.cubicTo(w*.56f,amp*1.8f,w*.56f,amp*.5f,w*.62f,amp*.25f);x.cubicTo(w*.72f,0f,w*.82f,amp,w,amp);x.lineTo(w,b.height().toFloat());x.lineTo(0f,b.height().toFloat());x.close();c.drawPath(x,p)};override fun setAlpha(a:Int){p.alpha=a};override fun setColorFilter(f:ColorFilter?){p.colorFilter=f};override fun getOpacity()=PixelFormat.OPAQUE}
class BirdSkyView(c:android.content.Context):View(c){private val p=Paint(1).apply{color=Color.BLACK;style=Paint.Style.STROKE;strokeWidth=4f;strokeCap=Paint.Cap.ROUND};private var t=0f;private val b=listOf(floatArrayOf(-.1f,.30f,1f),floatArrayOf(.2f,.47f,.75f),floatArrayOf(.55f,.22f,.9f),floatArrayOf(.78f,.40f,.65f));override fun onDraw(c:Canvas){super.onDraw(c);val w=width.toFloat();val h=height.toFloat();b.forEachIndexed{i,a->val x=((a[0]+t*(.13f+i*.018f))%1.25f)*w;val y=a[1]*h+sin(t*10+i)*5f;val s=dp(15)*a[2];val flap=sin(t*24+i)*s*.55f;c.save();c.translate(x,y);val path=Path();path.moveTo(0f,0f);path.cubicTo(-s*.3f,-flap*.3f,-s*.65f,-flap,-s,flap*.15f);path.moveTo(0f,0f);path.cubicTo(s*.3f,-flap*.3f,s*.65f,-flap,s,flap*.15f);c.drawPath(path,p);c.restore()};t+=.016f;postInvalidateOnAnimation()};private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()}
